In [26]:
# Alexandre-Theophile Vandermonde.
import numpy as np
import pandas as pd
k=np.array([1,2,3,4])
n=6

def Vandermonde(n,kvalue,increasing=False):
    if not increasing:
        decreasing_value = np.array([x**(n-1-i) for x in kvalue for i in range(n)]).reshape(kvalue.size,n)
        print(decreasing_value)
        #print("\n\n")
    else:
        incresing_value = np.array([x**i for x in kvalue for i in range(n)]).reshape(kvalue.size,n)
        print(incresing_value)

In [27]:
Vandermonde(n,k,True)

[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]]


In [28]:
Vandermonde(n,k,False)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]]


In [29]:
# Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3
numbers_series = pd.Series(array)
windows = numbers_series.rolling(window_size)
moving_averages = windows.mean()
moving_averages_list = moving_averages.tolist()
without_nans = moving_averages_list[window_size - 1:]
print(without_nans)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
